name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: echo username
        run: echo ${{ secrets.DOCKER_USERNAME }}
      - name: echo abc
        run: echo abc

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: docker build -t shibotong/download-automation:v1.0.7 .

      - name: Push Docker image to Docker Hub
        run: docker push shibotong/download-automation:v1.0.7
